### ISSUE TITLE
Rating fails at checking instance of rateable model

### ISSUE THREAD

**Issue by victorighalo** [rennokki/rating#8]
When I attempt to rate a model after following the configurations i get false from this

 ! $model instanceof Rater && ! $model instanceof Rating in CanRate Trait

**Comment by davidhenia** [comment]
I believe the check should be: `if (! $model instanceof Rateable && ! $this instanceof Rater) {`

**Comment by victorighalo** [comment]
> I believe the check should be: `if (! $model instanceof Rateable && ! $this instanceof Rater) {`

I copied the code from the Source code of the package

**Comment by rennokki** [comment]
This has been fixed in https://github.com/rennokki/rating/releases/tag/2.0.1
